baseURL = 'https://centre-for-music-and-science.github.io/'
languageCode = 'en-gb'
title = 'Centre for Music and Science'
theme = 'cms'

[params]
  description = "The Centre for Music and Science (CMS) supports both teaching and research into the science of music at the University of Cambridge."
  heroTitle = "Centre for Music and Science"
  heroSubtitle = "University of Cambridge"
  themesIntro = "The Centre for Music and Science (CMS) is divided into two working groups: the Music Cognition and Culture Group and the Music, Language, and Society Group."

buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
